SONGKICK_API_KEY: tnIoiwzydaoUPOrR

SPOTIFY_CLIENT_ID: c2ad8981609d4b11ab13252b21847689
SPOTIFY_SECRET: 9c36827575bd4defb36000e264e1509d

GOOGLE_CLIENT_ID: '833185403407-gm6791apta4g2ef6kbmvlol5blh32692.apps.googleusercontent.com'
GOOGLE_SECRET: 'w62mUrGA28f1kDdYTZGS_uJJ'

GOOGLE_PLACES_KEY: 'AIzaSyDsvcpDB8Lltum1czYr_53tXE5_99yCvLE'

EVENTBRITE_CLIENT_ID: '2VGT723BJZKJYWHIB3'
EVENTBRITE_SECRET: '3NLAE72WNQLDLE6VKWJ44VNDE3J3FYRRL2LNJLSZ4LEZSVCTMZ'

development:
  MAILER_HOST: "localhost:3000"

test:
  MAILER_HOST: "localhost:3000"

production:
  MAILER_HOST: "domain.com"
